// <auto-generated />
using System;
using H3_project.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace H3_project.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20231018105426_initialcreate")]
    partial class initialcreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("H3_project.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("H3_project.Models.Login", b =>
                {
                    b.Property<int>("LoginID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("LoginID");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("H3_project.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderID");

                    b.HasIndex("UserId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("H3_project.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("H3_project.Models.ProductOrderList", b =>
                {
                    b.Property<int>("ProductOrderListID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductOrderListID"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductOrderListID");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductOrderList");
                });

            modelBuilder.Entity("H3_project.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LoginId")
                        .HasColumnType("int");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<int?>("UsertypeID")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.HasIndex("LoginId")
                        .IsUnique()
                        .HasFilter("[LoginId] IS NOT NULL");

                    b.HasIndex("UsertypeID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("H3_project.Models.UserType", b =>
                {
                    b.Property<int>("UsertypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsertypeID"));

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("UserNameType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsertypeID");

                    b.ToTable("UserType");
                });

            modelBuilder.Entity("H3_project.Models.Login", b =>
                {
                    b.HasOne("H3_project.Models.UserType", "userType")
                        .WithMany("logins")
                        .HasForeignKey("UserTypeId");

                    b.Navigation("userType");
                });

            modelBuilder.Entity("H3_project.Models.Order", b =>
                {
                    b.HasOne("H3_project.Models.User", "user")
                        .WithMany("order")
                        .HasForeignKey("UserId");

                    b.Navigation("user");
                });

            modelBuilder.Entity("H3_project.Models.Product", b =>
                {
                    b.HasOne("H3_project.Models.Category", "category")
                        .WithMany("product")
                        .HasForeignKey("CategoryId");

                    b.Navigation("category");
                });

            modelBuilder.Entity("H3_project.Models.ProductOrderList", b =>
                {
                    b.HasOne("H3_project.Models.Order", "Orders")
                        .WithMany("orderlists")
                        .HasForeignKey("OrderId");

                    b.HasOne("H3_project.Models.Product", "Products")
                        .WithMany("orderlists")
                        .HasForeignKey("ProductId");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("H3_project.Models.User", b =>
                {
                    b.HasOne("H3_project.Models.Login", "login")
                        .WithOne("User")
                        .HasForeignKey("H3_project.Models.User", "LoginId");

                    b.HasOne("H3_project.Models.UserType", "userType")
                        .WithMany()
                        .HasForeignKey("UsertypeID");

                    b.Navigation("login");

                    b.Navigation("userType");
                });

            modelBuilder.Entity("H3_project.Models.Category", b =>
                {
                    b.Navigation("product");
                });

            modelBuilder.Entity("H3_project.Models.Login", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("H3_project.Models.Order", b =>
                {
                    b.Navigation("orderlists");
                });

            modelBuilder.Entity("H3_project.Models.Product", b =>
                {
                    b.Navigation("orderlists");
                });

            modelBuilder.Entity("H3_project.Models.User", b =>
                {
                    b.Navigation("order");
                });

            modelBuilder.Entity("H3_project.Models.UserType", b =>
                {
                    b.Navigation("logins");
                });
#pragma warning restore 612, 618
        }
    }
}
